name: iFeel
favicon: null
layout_spectrum: 0.42057497310452163
typography_spectrum: 0.17878542910329998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8175313898827881
  lightness: 0.595395470270887
  saturation: 0.6558444213587791
  rhythmicContrast: 0.2940122187137604
purpose: []
